spring.application.name=e-commerce3
 
# H2 Database (se reinicia al parar la app)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
 
 
# 1. Configuración de la Fuente de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db3?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
 
# 2. Driver específico (Cuidado aquí: si usas MySQL, NO menciones a H2)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
# 3. JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true