spring.application.name=e-commerce3
 
# 1. Configuracion de la Fuente de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db3?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
# 3. JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true